import logo2 from '../assets/image/load/logo2.png'
import logo3 from '../assets/image/load/logo3.png'
import logo4 from '../assets/image/load/logo4.png'
import loadIco1 from '../assets/image/load/loadIco1.png'
import loadIco2 from '../assets/image/load/loadIco2.png'
import loadIco3 from '../assets/image/load/loadIco3.png'
import loadIco4 from '../assets/image/load/loadIco4.png'
import loadIco5 from '../assets/image/load/loadIco5.png'
import loadIco6 from '../assets/image/load/loadIco6.png'
import loadIco7 from '../assets/image/load/loadIco7.png'
import loadIco8 from '../assets/image/load/loadIco8.png'
import loadIco9 from '../assets/image/load/loadIco9.png'
import cloud1 from '../assets/image/bg/cloud1.png'
import cloud2 from '../assets/image/bg/cloud2.png'
import cloud3 from '../assets/image/bg/cloud3.png'
import bg from '../assets/image/bg/bg.jpg'
import bg1 from '../assets/image/bg/1.png'
import bg2 from '../assets/image/bg/2.png'
import bg3 from '../assets/image/bg/3.png'
import bg4 from '../assets/image/bg/4.png'
import bg5 from '../assets/image/bg/5.png'
import bg6 from '../assets/image/bg/6.png'
import bg7 from '../assets/image/bg/7.png'
import bg8 from '../assets/image/bg/8.png'
import bg9 from '../assets/image/bg/9.png'
import bg10 from '../assets/image/bg/10.png'
import bg11 from '../assets/image/bg/11.png'
import bg12 from '../assets/image/bg/12.png'
import bg13 from '../assets/image/bg/13.png'
import bg14 from '../assets/image/bg/14.png'
import bg15 from '../assets/image/bg/15.png'
import bg16 from '../assets/image/bg/16.png'
import bg17 from '../assets/image/bg/17.png'
import bg18 from '../assets/image/bg/18.png'
import bg19 from '../assets/image/bg/19.png'
import bg20 from '../assets/image/bg/20.png'
import p1 from '../assets/image/pano/p1-1.png'
import p2 from '../assets/image/pano/p1-2.png'
import p3 from '../assets/image/pano/p2-1.png'
import p4 from '../assets/image/pano/p2-2.png'
import p5 from '../assets/image/pano/p2-3.png'
import p6 from '../assets/image/pano/p3-1.png'
import p7 from '../assets/image/pano/p3-2.png'
import p8 from '../assets/image/pano/p3-3.png'
import p9 from '../assets/image/pano/p3-4.png'
import p10 from '../assets/image/pano/p4-1.png'
import p11 from '../assets/image/pano/p4-2.png'
import p12 from '../assets/image/pano/p4-3.png'
import p13 from '../assets/image/pano/p4-4.png'
import p14 from '../assets/image/pano/p4-5.png'
import p15 from '../assets/image/pano/p5-1.png'
import p16 from '../assets/image/pano/p5-2.png'
import p17 from '../assets/image/pano/p5-3.png'
import p18 from '../assets/image/pano/p5-4.png'
import p19 from '../assets/image/pano/p5-5.png'
import p20 from '../assets/image/pano/p5-6.png'
import p21 from '../assets/image/pano/p6-1.png'
import p22 from '../assets/image/pano/p6-2.png'
import p23 from '../assets/image/pano/p6-3.png'
import p24 from '../assets/image/pano/p6-4.png'
import p25 from '../assets/image/pano/p6-5.png'
import p26 from '../assets/image/pano/p6-6.png'
import p27 from '../assets/image/pano/p7-1.png'
import p28 from '../assets/image/pano/p7-2.png'
import p29 from '../assets/image/pano/p7-3.png'
import p30 from '../assets/image/pano/p8-1.png'
import p31 from '../assets/image/pano/p8-2.png'
import p32 from '../assets/image/pano/p8-3.png'
import p33 from '../assets/image/pano/p8-4.png'
import p34 from '../assets/image/pano/p8-5.png'
import p35 from '../assets/image/pano/p8-6.png'

const imgData = {
	logo:[logo2,logo3,logo4],
	logoIco:[loadIco1,loadIco2,loadIco3,loadIco4,loadIco5,loadIco6,loadIco7,loadIco8,loadIco9],
	cloud:[cloud1,cloud2,cloud3],
	pageBg:[bg],
	bg:[bg1, bg2, bg3, bg4, bg5, bg6, bg7, bg8, bg9, bg10, bg11, bg12, bg13, bg14, bg15, bg16, bg17, bg18, bg19, bg20],
	pano:[p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p30, p31, p32, p33, p34,p35]
};
export default imgData